---
title: "iteration_and_listcols"
author: "Hanrui Li"
date: "2024-10-29"
output: github_document
---

```{r message=FALSE,warning=FALSE}
library(tidyverse)
library(rvest)

set.seed(1)
```

## Lists

You can put anything in a list.

```{r}
vec_numeric = 5:8
vec_char = c("My", "name", "is", "Jeff")
vec_logical = c(TRUE, TRUE, TRUE, FALSE)
```

```{r}
l = list(
  vec_numeric = 5:8,
  mat = matrix(1:8, nrow = 2, ncol = 4),
  vec_logical = c(TRUE, TRUE, FALSE, TRUE, FALSE, FALSE),
  summary = summary(rnorm(1000)))
```

```{r}
l

l$vec_numeric
l[[1]]
l[[1]][1:3]
mean(l[["vec_numeric"]])
```


## `for` loops

Create a new list.

```{r}
list_norms = 
  list(
    a = rnorm(20, 3, 1),
    b = rnorm(20, 0, 5),
    c = rnorm(20, 10, .2),
    d = rnorm(20, -3, 1)
  )

is.list(list_norms)
```

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}
```

I can apply the function to each list element.

```{r}
mean_and_sd(list_norms[[1]])
mean_and_sd(list_norms[[2]])
mean_and_sd(list_norms[[3]])
mean_and_sd(list_norms[[4]])
```

Let's use a `for` loop.

```{r}
output = vector("list", length = 4)

for (i in 1:4) {
  output[[i]] = mean_and_sd(list_norms[[i]])
}
```


## `map`

```{r}
output = map(list_norms, mean_and_sd)
output
```

```{r}
output = vector("list", length = 4)

for (i in 1:4) {
  output[[i]] = median(list_norms[[i]])
}

output = map(list_norms, median)
```


## `map` variants

```{r}
output = map_dbl(list_norms, median, .id = "input")

```














